services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: idontneedit:dev
    volumes:
      - .:/app
      - static-data:/app/static
      - /app/.venv
      - /app/__pycache__
