$ANSIBLE_VAULT;1.1;AES256
30333336633261626235393465623166376266313464663163343231636135383361306365653133
6633626335633965383934336336346230336130363936340a343438306362373163396265386536
62396539316138343961623935373534643733383065396139383732396464356531333434633862
3230343862306461310a663333613138363566653162626237363535346165616436353838303562
39396236366235643064393637373437623435613433356139663839303038363736333262633230
39383863663835323938613438363134343162656563333932383661613139333839626231373538
61643962323137333138363334666364353263663664326535383437336631653265643164343539
38386234376239653931323963343736383036656330386363303033623134316466303834316561
62376632353136316138663362373566643466373537366266663565336431366465393633383034
65643637356361356361323934663463373635666562663335336161623564616534333232383230
30656134306236356365656662363761636363313037343964326631653964613464303932633034
39323834633631333930
