$ANSIBLE_VAULT;1.1;AES256
30613238653936646365643862313738353663356631303936323638366330386137626465346439
3331626264333062636463393834386336616561326264610a323330333638663436356637393464
61303731623831326539663433316562356634376165623932633364343833646561333964353434
3033376130386239360a613362393532633838373763646163326239343238366331303230386634
34376563643537303663623332643133616662616435373063306465376633333033393331306364
64373466663531663830346136316365633730333436613139663630393739313365313338613638
31623035646564326232363962633234376365323634323039666531303837376431613062333238
62396634313766643734
